version: '3.0'

services:
  nginx: 
    image: nginx:1.23.3-alpine-slim
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/static:/usr/share/nginx/html"

  app:
    image: employee:latest
    environment:
      MONGO_URI: mongodb://mongodb:27017/employees

  mongodb:
    image: mongo:6.0.4

networks:
  network1:
    name: portfolio_default
    external: true