version: '3.0'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine-slim

  app:
    container_name: app
    image: employees:latest
    environment:
      MONGO_URI: mongodb://mongodb:27017/employees

  mongodb:
    container_name: mongodb
    image: mongo:6.0.4

networks:
  # same as jenkins' network 
  default:
    name: jenkins_default
    external: true